export const directAsyncType = "DIRECT_TYPE"
export const homeAsyncType = "HOME_TYPE"
export const homelistAsyncType = "HOME_LIST_TYPE"
export const activityAsyncType = "ACTIVITY_TYPE"
export const gamedetailAsyncType = "GAMEDEATIL_TYPE"
